- hosts: all
  become: yes
  tasks:
    - name: update first
      apt:
        update_cache: yes
    - name: install 5 packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: add repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    - name: update again
      apt:
        update_cache: yes
    - name: install docker engine
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: start docker service
      service:
        name: docker
        state: started
    - name: add user to docker group
      user:
        name: swaroop
        shell: /bin/bash
        groups: docker
        append: yes

