- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: kvswp22
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /media/iamadmin/Space4all/Devops/kvswp22-dadae35ef29d.json
      zone: "us-west1-b"
      region: "us-west1"

  tasks:
   - name: create a disk
     gcp_compute_instance:
         name: "{{ item }}"
         machine_type: n1-standard-1
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         state: present
     loop:
       - instance-1
       - instance-2
       - instance-3
